apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /tmp/nginx.conf
          subPath: nginx.conf
        envFrom:
        - secretRef:
            name: nginx-secret
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config
